<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxytaxO\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxytaxO/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXxytaxO.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXxytaxO\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXxytaxO\App_KernelDevDebugContainer([
    'container.build_hash' => 'XxytaxO',
    'container.build_id' => 'da19138a',
    'container.build_time' => 1597780846,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxytaxO');
